language: node_js

node_js:
  - 7
  - 6
  - 4

script:
  - npm install -g bower grunt-cli
  - bower install --allow-root
  - npm install --production
  - npm install --only=dev
  - grunt build:prod
  - node server/app.js


notifications:
  slack: phatpham9:AuqNWMV3FScfBQmK4ieHov0f
