version: "2"
services:
  web:
    container_name: dashboard
    image: phatpham9/ddnode
    network_mode: bridge
    # link to external container
    external_links:
      - mongo:mongo
    # export env variable
    environment:
      - DB_HOST=mongo
    # expose ports to host
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:35729:35729
    # shared volumes with host
    volumes:
      - /path/to/dashboard:/app
    # start script
    command: npm start
